version: '2'

services:
  php:
    build: app
    ports:
      - "30080:80"
      - "30443:443"
    volumes:
      - ./app/dojo-basic:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dojo
      - MYSQL_DATABASE=dojo_basic
